<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tenebris-Portrait.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="ViewModel\HeroCard.xaml" />
    <Page Remove="ViewModel\InventoryCard.xaml" />
    <Page Remove="ViewModel\SpellCard.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ViewModel\InventoryCard.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
      <Generator>MSBuild:Compile</Generator>
    </Content>
    <Content Include="ViewModel\SpellCard.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>MSBuild:Compile</Generator>
    </Content>
    <Content Include="ViewModel\HeroCard.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="tenebris-Portrait.png" />
  </ItemGroup>

</Project>
